// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB_apiKey'),
    appId: dotenv.get('FIREBASE_WEB_appId'),
    messagingSenderId: dotenv.get('FIREBASE_WEB_messagingSenderId'),
    projectId: dotenv.get('FIREBASE_WEB_projectId'),
    authDomain: dotenv.get('FIREBASE_WEB_authDomain'),
    storageBucket: dotenv.get('FIREBASE_WEB_storageBucket'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID_apiKey'),
    appId: dotenv.get('FIREBASE_ANDROID_appId'),
    messagingSenderId: dotenv.get('FIREBASE_ANDROID_messagingSenderId'),
    projectId: dotenv.get('FIREBASE_ANDROID_projectId'),
    storageBucket: dotenv.get('FIREBASE_ANDROID_storageBucket'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS_apiKey'),
    appId: dotenv.get('FIREBASE_IOS_appId'),
    messagingSenderId: dotenv.get('FIREBASE_IOS_messagingSenderId'),
    projectId: dotenv.get('FIREBASE_IOS_projectId'),
    storageBucket: dotenv.get('FIREBASE_IOS_storageBucket'),
    iosBundleId: dotenv.get('FIREBASE_IOS_iosBundleId'),
  );
}
